# Generated by Django 4.0 on 2023-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_structure',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_structure',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
