# Generated by Django 4.0 on 2023-01-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structure', '0002_alter_data_structure_name_alter_data_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_structure',
            name='ranking',
            field=models.IntegerField(default=100, max_length=700),
        ),
    ]
