# Generated by Django 4.0 on 2023-01-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structure', '0003_data_structure_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_structure',
            name='ranking',
            field=models.IntegerField(default=100),
        ),
    ]
