# Generated by Django 4.0 on 2023-02-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structure', '0004_alter_data_structure_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_structure',
            name='data',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='data_structure',
            name='img',
            field=models.ImageField(blank=True, upload_to='sample_image'),
        ),
        migrations.AlterField(
            model_name='data_structure',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_structure',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
