# Generated by Django 4.0 on 2022-06-03 08:04

from django.db import migrations, models
import django.utils.timezone
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarydata',
            name='dates',
            field=models.DateField(auto_created=sqlalchemy.sql.expression.true, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
