# Generated by Django 4.0 on 2023-06-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diarydata_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diarydata',
            table='Note',
        ),
    ]
