# Generated by Django 4.0 on 2023-06-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diarydata_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diarydata',
            new_name='Notedata',
        ),
    ]
