# Generated by Django 4.0 on 2023-06-17 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_rename_diarydata_notedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedata',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
