# Generated by Django 4.0 on 2022-05-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=30)),
                ('URL', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='apps')),
            ],
        ),
    ]
