# Generated by Django 4.0 on 2022-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flutter_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=30)),
                ('codes', models.CharField(max_length=10000)),
                ('img', models.ImageField(upload_to='alexander')),
            ],
        ),
    ]
