# Generated by Django 4.0 on 2022-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutter_data',
            name='codes',
            field=models.TextField(max_length=10000),
        ),
    ]
