# Generated by Django 4.0 on 2022-08-26 15:18

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0003_alter_flutter_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutter_data',
            name='img',
            field=models.ImageField(default=sqlalchemy.sql.expression.null, null=True, upload_to='alexander'),
        ),
    ]
