# Generated by Django 4.0 on 2022-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0005_alter_flutter_data_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutter_data',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
