# Generated by Django 4.0 on 2022-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0007_c_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='img',
            field=models.ImageField(default='defaults.jpg', null=True, upload_to='Calexander'),
        ),
        migrations.AlterField(
            model_name='flutter_data',
            name='img',
            field=models.ImageField(default='defaults.jpg', null=True, upload_to='alexander'),
        ),
    ]
