# Generated by Django 4.0 on 2022-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0008_alter_c_data_img_alter_flutter_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flutter_data',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
