# Generated by Django 4.0 on 2022-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0009_alter_c_data_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutter_data',
            name='description',
            field=models.TextField(default='null', max_length=1000, null=True),
        ),
    ]
