# Generated by Django 4.0 on 2022-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0010_alter_flutter_data_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='description',
            field=models.TextField(default='null', max_length=1000, null=True),
        ),
    ]
