# Generated by Django 4.0 on 2022-11-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0011_alter_c_data_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='django_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('codes', models.TextField(max_length=10000)),
                ('img', models.ImageField(default='DIARY.jfif', null=True, upload_to='python')),
            ],
        ),
    ]
