# Generated by Django 4.0 on 2022-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0013_alter_django_data_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='solidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('codes', models.TextField(max_length=10000)),
                ('img', models.ImageField(default='defaults.jpg', null=True, upload_to='python')),
            ],
        ),
        migrations.CreateModel(
            name='web3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('codes', models.TextField(max_length=10000)),
                ('img', models.ImageField(default='defaults.jpg', null=True, upload_to='python')),
            ],
        ),
    ]
