# Generated by Django 4.0 on 2022-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0015_alter_django_data_img_alter_solidity_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_data',
            name='description',
            field=models.TextField(default='null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solidity',
            name='description',
            field=models.TextField(default='null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='web3',
            name='description',
            field=models.TextField(default='null', max_length=1000, null=True),
        ),
    ]
